name: Deploy to VM

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs on a GitHub-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 52.200.116.41 >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ubuntu@52.200.116.41 << 'EOF'
          cd /home/ubuntu/Calmpanion
          git pull origin main
          source /home/ubuntu/Calmpanion/venv/bin/activate
          pip install -r requirements.txt  # If needed
          systemctl restart calmpanion.service  # Restart if using a service
        EOF
